# Default values for podinfo.

replicaCount: 1
logLevel: info
backend: #http://backend-podinfo:9898/echo
backends: []

ui:
  color: "#34577c"
  message: ""
  logo: ""

faults:
  delay: false
  error: false
  unhealthy: false
  unready: false

httpServer:
  timeout: 30s

h2c:
  enabled: false

image:
  repository: stefanprodan/podinfo
  tag: 3.2.0
  pullPolicy: IfNotPresent

service:
  enabled: false
  type: ClusterIP
  metricsPort: 9797
  httpPort: 9898
  externalPort: 9898
  grpcPort: 9999
  grpcService: podinfo
  nodePort: 31198

hpa:
  enabled: true
  maxReplicas: 2
  memory: 256Mi

serviceAccount:
  enabled: false
  name:

linkerd:
  profile:
    enabled: false

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
  path: /*
  hosts:
    - podinfo.local
  tls: []

resources:
  limits:
  requests:
    cpu: 2m
    memory: 16Mi

nodeSelector: {}

tolerations: []

affinity: {}

