name: event

on:
  repository_dispatch:
    types:
      - HelmRelease/podinfo-hr-0.helm-benchmark

permissions:
  contents: read

jobs:
  flux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Handle Flux event
        run: |
          echo '${{ toJson(github.event.client_payload) }}' | jq
      - name: Extract Helm chart version
        run: |
          VERSION=$(echo ${{ github.event.client_payload.metadata.revision }} | cut -d '@' -f1)
          echo $VERSION
